language: python
python:
  - 2.7

env:
  - CFLAGS="-I/usr/include/gdal -I$VIRTUAL_ENV/lib/python2.7/site-packages/numpy/core/include"

before_install:
  - sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
  - sudo apt-get -qq update
  - sudo apt-get -qq install libgdal-dev

install: 
  - pip install -r requirements.txt
  - pip install coveralls

script: coverage run --source=greenwich setup.py test
after_success: coveralls
