language: python
python:
  - 2.7
  - 3.5

env:
  - CFLAGS=-I/usr/include/gdal

before_install:
  - sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
  - sudo apt-get -qq update
  - sudo apt-get -y install libgdal-dev

install:
  - pip install -r requirements.txt
  - pip install coveralls

script: coverage run --source=greenwich setup.py test
after_success: coveralls
