language: python
python:
  - 2.7

install: 
  - pip install --use-mirrors -r requirements.txt
  - pip install coveralls

script: coverage run --source=greenwich setup.py test
after_success: coveralls
